"""
Django settings for abhivarna project.

Generated by 'django-admin startproject' using Django 1.8.13.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import datetime


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lk^1mpt)gfjciljo-kbaq+qd(zbq@11611f_s6ua*9+f!vrxeh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'main',
    'tracker',
    'ticketing_system'

)



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
    ),
}



JWT_AUTH = {
    'JWT_ENCODE_HANDLER':
    'rest_framework_jwt.utils.jwt_encode_handler',

    'JWT_DECODE_HANDLER':
    'rest_framework_jwt.utils.jwt_decode_handler',

    'JWT_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_payload_handler',

    'JWT_PAYLOAD_GET_USER_ID_HANDLER':
    'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',
    'JWT_RESPONSE_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_response_payload_handler',
    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_GET_USER_SECRET_KEY': None,
    'JWT_PUBLIC_KEY': None,
    'JWT_PRIVATE_KEY': None,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(minutes=600),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,
    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_AUTH_HEADER_PREFIX': 'ACR',
    'JWT_AUTH_COOKIE': None,

}

ROOT_URLCONF = 'Gateway.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "static", "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Gateway.wsgi.application'
# ASGI_APPLICATION = "Gateway.routing.application"
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
         'NAME': 'GATEWAY2',
        'USER': 'postgres',
        'PASSWORD': 'gateway',
        # 'PASSWORD': 'none',
        'PORT': '5432',
        'HOST': '172.16.41.161',
        # 'HOST': 'localhost',
    },


    # 'swipe': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'aeonasp',
    #     'USER': 'sa',
    #     'PASSWORD': 'test',
    #     'HOST': '172.16.51.193',
    #     'PORT': '',
    #     'OPTIONS': {
    #         'driver':'ODBC Driver 13 for SQL Server',
    #         'Trusted_Connection':'yes',
    #     }
    #
    # },

}

AUTH_USER_MODEL = "main.User"
DATA_UPLOAD_MAX_NUMBER_FIELDS = 102400


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR,"static/")


STATICFILES_DIRS = (
        os.path.join(BASE_DIR, "static", "static"),
    )

EMAIL_USE_TLS = False
EMAIL_HOST = 'mail.dqentertainment.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

DEFUALT_PASSWORD = "DQE@123"
PIPELINE_WISE_PROCESS = {
    'shot': ['layout', 'blocking', 'lip_sync', 'secondary', 'fx', 'mg', 'set_dressing', 'hair_sim', 'cloth_sim',
             'lighting', 'comp', 'fur_sim', 'scene_matte'],
    'asset': ['modeling', 'texturing', 'rigging', 'master_lighting', 'asset_comp', 'asset_hair', 'asset_fur', 'facial',
              'matte_paint','asset_cloth','asset_fx','vfx_element','uv']
}

GRADES = {'H1': 'High Paid', 'P1': 'P1', 'P2': 'P2', 'P3': 'P3', 'P4': 'P4', 'P5': 'P5', 'NA': 'N/A'}

ROLES = {"Artist": "Artist", "Supervisor": "Supervisor",
              "Quality Incharge": "Quality Incharge","PA":"PA","PC":"PC"}

PROJECT_WISE_ROLES = ['Director','Client','Admin','Manager','Superior','HR']

AVAILABLE_REVIEW_STATUS = ['Approved','Retake','Pending']

DEFAULT_PROJECT_CONF = [{'process': 'matte_painting', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'cd_review', 'review': 'NA', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}, {'process': 'blocking', 'internal_authority': '', 'external_percent': '', 'internal_percent': '', 'external_authority': '', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'N/A'}, {'process': 'lip_sync', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}, {'process': 'asset_hair', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'upload', 'review': 'NA', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'NA', 'client_review': 'NA'}, 'when_twenty_percent': 'master_lighting'}, {'process': 'comp', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}, {'process': 'mg', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}, {'process': 'scene_matte', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'N/A'}, {'process': 'lighting', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}, {'process': 'fx', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}, {'process': 'secondary', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}, {'process': 'layout', 'internal_authority': 'review', 'external_percent': '0', 'internal_percent': '100', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'N/A'}, {'process': 'set_dressing', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'lighting'}, {'process': 'cloth_sim', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'NA', 'review': 'cd_review', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'upload', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}, {'process': 'rigging', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'upload', 'review': 'NA', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'NA', 'client_review': 'NA'}, 'when_twenty_percent': 'N/A'}, {'process': 'texturing', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'upload', 'review': 'NA', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'NA', 'client_review': 'NA'}, 'when_twenty_percent': 'N/A'}, {'process': 'facial', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'upload', 'review': 'NA', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'NA', 'client_review': 'NA'}, 'when_twenty_percent': 'master_lighting'}, {'process': 'modeling', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'upload', 'review': 'NA', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'NA', 'client_review': 'NA'}, 'when_twenty_percent': 'secondary'}, {'process': 'master_lighting', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'upload', 'review': 'NA', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'NA', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}, {'process': 'asset_comp', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'upload', 'review': 'NA', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'NA', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}, {'process': 'asset_fx', 'internal_authority': 'review', 'external_percent': '20', 'internal_percent': '80', 'external_authority': 'upload', 'when_create_new_task': {'QC': 'upload', 'review': 'NA', 'upload': 'NA', 'cleanup': 'NA', 'cd_review': 'NA', 'client_review': 'NA'}, 'when_twenty_percent': 'comp'}]

SCHEDULE_WORKING_TIME = {'General':{'time_in':'0930','time_out':'1830','schedule_time':'0930','name':'General','minutes':570},
                        'A':{'time_in':'0600','time_out':'1400','schedule_time':'0600','name':'A','minutes':480 },
                        'C':{'time_in':'2200','time_out':'0600','schedule_time':'2200','name':'C','minutes':480},
                        'B':{'time_in':'1400','time_out':'2200','schedule_time':'1400','name':'B','minutes':480},
                        'Night':{'time_in':'2200','time_out':'2200','schedule_time':'2200','name':'Night','minutes':480},
                    }

MONTH_CYCLE_DATE = 30
import calendar
last_day = calendar.monthrange(datetime.datetime.now().date().year,datetime.datetime.now().date().month)
MONTH_CYCLE_DATE = last_day[1]
ASSET_TYPES = ['char','prop','set','vehicle','animal','generic','setprop','mg','vfx', 'matte']
